apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-example
  labels:
    app: k8s-example
    tier: front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-example
      tier: front
  template:
    metadata:
      labels:
        app: k8s-example
        tier: front
    spec:
      containers:
      - name: vue-example
        image: lusyoe/vue-example
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15

---
apiVersion: v1
kind: Service
metadata:
  name: k8s-example
  labels:
    app: k8s-example
    tier: front
spec:
  selector:
    app: k8s-example
    tier: front
  ports:
  - port: 80
    name: k8s-front

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: vue-example
spec:
  rules:
  - host: vue.k8s-example.com
    http:
      paths:
      - backend:
          serviceName: k8s-example
          servicePort: k8s-front
